# event_id: [type_of_bg, [name_object_of_character, that_char_talk_in_moment, position_id_obj: 0 (only_bg),1 (right), 2 (left)]]
events_talks = {
    "1": ["bg_zu_front_house", 
    ["Zu_obj", "Não podemos competir contra os carros da polícia.\nDa última vez que eles vieram aqui eu perdi minha mulher.\nEu não gosto deles. Todo ano, toda vez é isso.", 1], 
    ["Anne_obj", "Eu ti entendo.\nQueria poder fazer algo, mas... num sei.", 1], 
    ["Zu_obj", "Nem se preocupe com isso, não.\nTudo que cê tem que fazer agora é fazer o melhor tempo na corrida.\nBora se preparar?", 2],
    ["Anne_obj", "Bora!", 1], 
    ["Zu_obj", "Beleza!", 2]],
    "2": ["bg_iua_into_house",
     ["Iuá_obj", "Embora o terreno seja difícil, temos algumas pistas no início da\nfloresta...", 1],
     ["Anne_obj", "Sério? Isso num sabia.", 1],
     ["Iuá_obj", "Tome cuidado com os espíritos da floresta. Eles podem trazer algum\nmal. Antigas e antigos indígenas que não\ntiveramenterros dignos vagam pela floresta\ne podem te causar algum mau.", 2],
     ["Anne_obj", "Nem se preocupe! Eu não tenho medo!", 1],
     ["Iuá_obj", "Não é medo.", 2],
     ["Anne_obj", "Oxi! E é o quê?", 1],
     ["Iuá_obj", "Respeito! Eles existem. Eles não sabem o quê causam pra ti.\nElas e eles sofrem muito por não puderem “desaparecer”", 2],
     ["Anne_obj", "Desculpa! Cê tem razão, mas por que eles não tiveram enterro?", 1],
     ["Iuá_obj", "Infelizmente, os home branco foram lá e mataram elas e eles\npor terra, gado, ouro. Essas coisas de valor pra os branco.", 2],
     ["Anne_obj", "Que triste. Eles vagam sem rumo e sem saber pra onde vão…", 1],
     ["Iuá_obj", "Tudo bem, amiga. A mãe terra esta com a gente. As coisa vão mudar.", 2],
     ["Anne_obj", "Tá certo.", 1]],
    "3": ["bg_into_moacir_house", 
    ["Anne_obj", "Não tendi porque ali assumiu seu machismo.\nMachismo é algo estrutural e ruim.\nDeveria ser mortalmente evitado.", 1], 
    ["Moacir_obj", "Exatamente por isso. É algo que esta em todos os lugares, em mim e você.\n Antes de olhar para os outros, eu olhei para mim mesmo e...", 2], 
    ["Moacir_obj", "vi que precisava melhorar também se eu quisesse que não existisse estas coisas más;\ncomo racismo e xenofobia...", 2], 
    ["Moacir_obj", "Mais do que apontar o dedo na cara de alguém,\neu resolvi mudar a mim mesmo.", 2], 
    ["Anne_obj", "Mas...", 1],
    ["Moacir_obj", "Você procura evitar tratar destas questões com seus colegas?", 2], 
    ["Anne_obj", "Não. É que...", 1],
    ["Moacir_obj", "Seu mundo nunca mudará, jovem.", 2], 
    ["Anne_obj", "Tendi o que cê fez. Desculpa.", 1], 
    ["Moacir_obj", "Tudo bem. Olhe para minha idade.\nTou quase um pai de santo já, então saber destas coisas é fácil.", 2], 
    ["Moacir_obj", "Além disso, ao sair do terreiro mais cedo vi você\nse impondo muito diante daquele jovem armado. Parabéns!"],
    ["Anne_obj", "Brigada!",1],
    ["Moacir_obj", "Depois vo ter que falar com ele, por sinal;\nmas vamos ao que interessa.\nGostei d’ocê e cê quer vencer, né?", 2], 
    ["Anne_obj", "Claro!", 1], 
    ["Moacir_obj", "Então vamos nos preparar.", 2]],
    "4": ["bg_carlos_intro", 
    ["Carlos_obj", "Opa, gata! Tudo bom!?", 1], 
    ["Anne_obj", "Tudo! Boa tarde!", 1], 
    ["Carlos_obj", "Boa!", 2],
    ["Traficante_Armado", "Quê que essa mulé quer, hein?\nSua bitch!?", 2], 
    ["Anne_obj", "Sou puta de ninguém porque quero falar com outra pessoa de sexo\noposto, não, e outra, eu tô falando com cê,\npor acaso?", 1], 
    ["Traficante_Armado", "É o quê, quenga? Cê me respeite, viu?", 2], 
    ["Anne_obj", "Se não vai fazer o quê? Me matar?\nAqui quem me faltô respeito foi você, viu?\nIsso é magoa.\nPorque na pista já ganhei de cê antes, otário.", 1], 
    ["bg_only", "Os outros ao redor vaiam e é possível ouvir as falas\n“Carai! Nessa cê morreu Marquinhos!” e “Se fudeu!” ao fundo:\nUuuuuuuu! - vaia coletiva.", 0], 
    ["Traficante_Armado", "Oxi! Olha...", 2], 
    ["Carlos_obj", "Ela tá certa. Vacilou feio, mano", 2], 
    ["Carlos_obj", "Olha, meu nome é Carlos. Fala o que cê quer?", 2], 
    ["Anne_obj", "É você que gerencia as corridas de nível 1.\nComo faço pra participar do RUA?", 1],
    ["Carlos_obj", "Sou eu sim. Massa! Seja bem vinda.\nFique a vontade pra se enturmar com as meninas e meninos daqui.\nSó gente boa! Me dá seu nome compreto, celular e otras coisas.\nEu vou anotar e repassar pra Terceira, no fim das contas ela que\nmanda.", 2], 
    ["Anne_obj", "Beleza. Meu nome é Anne Gizza da Iara Bonita e Dandara.\nMeu número é...", 1]],
    "5": ["bg_intro_game",
     ["Senhor", "Faz muito tempo que a burguesia reclamava de uns incômodo\nadvindo das pessoas habitantes da comunidade\nribeirinha do Cortiço de Cabeça de Gato.\nEles recramava e recramava na rádia que nôis era doença e era feio.", 0],
     ["Senher", "Eles então começaram\ncom essas cosas de mudar, de tirar, de obter posse; quando vimos\nchego aqui uma orde de juiz maldoso\n– tosse interrompe a fala dele por um momento.", 0],
     ["Senhor", "Esta orde dizia pra nôis sair de nossas casa,\nque aquelas casa nossa eles precisavam pegar e pegar o terreno.\nA maioria fico lá, como eu. Porque nascemo e crescemo e… e depois\n", 0],
     ["Senhor", "de tanto tempo – mais uma pausa inesperada por conta da\ntosse – deveríamos sair do lugar. Não pode. Isso tá errado.", 0],
     ["Senhor", "Perdemo tudo. Foi tudo destruído.\nQuase morri na mão daqueles capangas deles que vestem aquelas\nfarda. Perdemo… Perdemo mermo.", 0],
     ["Senhor", "Eu consigo me lembrar, até hoje! Até hoje!\nDaqueles carros, daquelas armaduras...\nmatano meu amor.", 0],
     ["Senhor", "Então subimo o morro e invadimo o lixão. Moramo aqui a...\nagora. Na Favela do Baixo do Reginaldo. Té quando eles vorta de novo.\nSei lá! Hoje sobrevivemo ainda da pesca, mas andamo muito\naté chegar lá, mas alguns sobrevive do lixo.", 0],
     ["Senhor", "Então veio esse doençero,\nesse lixo todo de computador, de carro, de comida, de tudo.\nTudo isso mata.", 0],
     ["Senhor", "Eu amava minha terra. Por que isso? De todo modo,\ntenho minhas filhas e netas... e\ntenho que continuar, né? Não posso parar antes de\nver elas florescer e fica bem.", 0]]
}